services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cr8s
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cr8s
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
